@cd/d "%~dp0"
@echo off
SET MYDIR=%CD%
SET PATH=%MYDIR%\;%PATH%
certutil -addstore "Root" "isrg-root-x1-cross-signed.crt"
certutil -addstore "Root" "isrg-root-x2-cross-signed.crt"
certutil -addstore "Root" "letsencryptauthorityx1.crt"
certutil -addstore "Root" "letsencryptauthorityx2.crt"
certutil -addstore "Root" "letsencryptauthorityx3.crt"
certutil -addstore "Root" "letsencryptauthorityx4.crt"
certutil -addstore "Root" "lets-encrypt-e1.crt"
certutil -addstore "Root" "lets-encrypt-e2.crt"
certutil -addstore "Root" "lets-encrypt-r3.crt"
certutil -addstore "Root" "lets-encrypt-r4.crt"
certutil -addstore "Root" "lets-encrypt-x1-cross-signed.crt"
certutil -addstore "Root" "lets-encrypt-x2-cross-signed.crt"
certutil -addstore "Root" "lets-encrypt-x3-cross-signed.crt"
certutil -addstore "Root" "lets-encrypt-x4-cross-signed.crt"

certutil -addstore "CA" "isrg-root-x1-cross-signed.crt"
certutil -addstore "CA" "isrg-root-x2-cross-signed.crt"
certutil -addstore "CA" "letsencryptauthorityx1.crt"
certutil -addstore "CA" "letsencryptauthorityx2.crt"
certutil -addstore "CA" "letsencryptauthorityx3.crt"
certutil -addstore "CA" "letsencryptauthorityx4.crt"
certutil -addstore "CA" "lets-encrypt-e1.crt"
certutil -addstore "CA" "lets-encrypt-e2.crt"
certutil -addstore "CA" "lets-encrypt-r3.crt"
certutil -addstore "CA" "lets-encrypt-r4.crt"
certutil -addstore "CA" "lets-encrypt-x1-cross-signed.crt"
certutil -addstore "CA" "lets-encrypt-x2-cross-signed.crt"
certutil -addstore "CA" "lets-encrypt-x3-cross-signed.crt"
certutil -addstore "CA" "lets-encrypt-x4-cross-signed.crt"
pause
